name: Deploy

on:
  push: 
      branches:
      - main

jobs:
  deploy_lambda:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test